version: '3.9'
services:
  backend:
    build: ./app
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/moysklad
      - REDIS_URL=redis://redis:6379/0
      - MOYSKLAD_TOKEN=your_moysklad_token
    volumes:
      - ./app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  celery:
    build: ./app
    depends_on:
      - backend
      - redis
    command: celery -A worker.app worker --loglevel=info
    volumes:
      - ./app:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/moysklad
      - REDIS_URL=redis://redis:6379/0
      - MOYSKLAD_TOKEN=your_moysklad_token

  beat:
    build: ./app
    depends_on:
      - backend
      - redis
    command: celery -A worker.app beat --loglevel=info
    volumes:
      - ./app:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/moysklad
      - REDIS_URL=redis://redis:6379/0
      - MOYSKLAD_TOKEN=your_moysklad_token

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moysklad
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6
    restart: always
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata: